services:
  - type: web
    name: baseball_app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: ADMIN_CODE
        sync: false
      - key: DATABASE_URL
        sync: false
        value: "postgresql://postgres.ebllssdqrwedkyjwuedj:Baby100412!@aws-1-ap-south-1.pooler.supabase.com:5432/postgres"
    region: oregon
